### ISSUE TITLE
incorrect structure ProductAttribute

### ISSUE THREAD

**Issue by RB-PRO** [hiscaler/woocommerce-go#2]
https://github.com/hiscaler/woocommerce-go/blob/main/entity/product_attribute.go
its incorrect. pks check WC api doc http://woocommerce.github.io/woocommerce-rest-api-docs/#product-properties

**correct**:

> package entity
> 
> // ProductAttribute product attribute properties
> type ProductAttribute struct {
> 	/*
> 		ID          int    `json:"id"`
> 		Name        string `json:"name"`
> 		Slug        string `json:"slug"`
> 		Type        string `json:"type"`
> 		OrderBy     string `json:"order_by"`
> 		HasArchives bool   `json:"has_archives"`
> 	*/
> 	ID        int      `json:"id"`        // Attribute ID.
> 	Name      string   `json:"name"`      // Attribute name.
> 	Position  int      `json:"position"`  // Attribute position.
> 	Visible   bool     `json:"visible"`   // Define if the attribute is visible on the "Additional information" tab in the product's page. Default is false
> 	Variation bool     `json:"variation"` // Define if the attribute can be used as variation. Default is false
> 	Options   []string `json:"options"`   // List of available term names of the attribute
> }

**Comment by hiscaler** [comment]
@RB-PRO 
ProductAttribute is http://woocommerce.github.io/woocommerce-rest-api-docs/#product-attributes
Product.Attribute is entity.ProductAttributeItem
