### ISSUE TITLE
SettingOption error

### ISSUE THREAD

**Issue by qq2161811** [hiscaler/woocommerce-go#3]
RestApi document SettingOption id must string
![image](https://github.com/hiscaler/woocommerce-go/assets/31003386/a311cb86-c845-417a-b3e8-b75da9370593)

But package SettingOption id must int
![image](https://github.com/hiscaler/woocommerce-go/assets/31003386/9782dd86-aaac-49b8-8728-7d15e684b375)

This should be a loophole, could you please correct it? Thank you

**Comment by hiscaler** [comment]
Let me see, Thank you feedback.

**Comment by hiscaler** [comment]
Is fixed.
